### ISSUE TITLE
How To Use in Windows

### ISSUE THREAD

**Issue by aask1357** [modum-app/build-namuwiki-sql#2]
I'm using windows 10, python 2.7.14
I deleted the code
`import signal`
`signal.signal(signal.SIGPIPE, signal.SIG_DFL)`
as windows doesn't support SIGPIPE

At the folder, I entered the command
`>python build-namuwiki-sql.py`
as a result, an sql file with only definitions without contents is made

Don't know when and where to use command
`time 7zcat namuwiki0000.7z | ./build-namuwiki-sql.py`

How can I transfer a database dump into a sqlite3 file?

**Comment by yeonwoonj** [comment]
1. Install 7-zip and Python2
2. Download the latest version of `sqlite3.dll` from [sqlite.org](http://www.sqlite.org/download.html); see `Precompiled Binaries for Windows` section
3. Replace `C:\Python27\DLLs\sqlite3.dll` with the one in the step 1
4. Open cmd and make sure that both 7z and python are in PATH
5. Install pylzma: `python -m pip install pylzma`
6. Execute `7z e -so -bd <path\to\namuwiki.7z> | python build-namuwiki-sql.py`
